### ISSUE TITLE
亲测耗时太长

### ISSUE THREAD

**Issue by zhuangzaiku** [idealspark/ZhiShiWenDa-Helper#2]
按下Enter键到百度到关键字，平均耗时8秒，而且容易出现乱码，可用性太低

**Comment by lihuangshuaige** [comment]
Traceback (most recent call last):
  File "helper.py", line 58, in <module>
    driver.find_element_by_id('kw').send_keys(Keys.CONTROL, 'a')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 351, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 955, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"kw"}
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by lihuangshuaige** [comment]
有时会出现上面的东东  是啥意思啊

**Comment by lihuangshuaige** [comment]
耗时3s -4s

**Comment by asdasadasf** [comment]
使用的移动热点，耗时2s左右

**Comment by zzq56** [comment]
热点耗时不长但是答到后面，莫名其妙提交不了答案，原因你懂的。。

**Comment by Jerome-MJ** [comment]
我自己写了个 
耗时1s 
不过不能使用adb截图  ，adb截图太卡

**Comment by zhuangzaiku** [comment]
@lihuangshuaige 估计环境配置有问题吧

**Comment by zhuangzaiku** [comment]
我自己实现了一个，用AccessibilityService监听窗口变化，找到对应的TextView，可以抓到文字，配合悬浮窗百度搜索，零点几秒即可搜索，不过对于混淆或者加固的app无效
